ci:
  autoupdate_schedule: "monthly"

default_language_version:
  python: "python3.13"

repos:
  - repo: "meta"
    hooks:
      - id: "check-hooks-apply"
      - id: "check-useless-excludes"

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "3e8a8703264a2f4a69428a0aa4dcb512790b2c8c"  # frozen: v6.0.0
    hooks:
      - id: "check-added-large-files"
      - id: "check-merge-conflict"
      - id: "check-yaml"
      - id: "end-of-file-fixer"
        exclude: "\\.xml"
      - id: "mixed-line-ending"
        exclude: "\\.xml"
        args:
          - "--fix=lf"
      - id: "trailing-whitespace"
        exclude: "\\.xml"

  - repo: "https://github.com/asottile/pyupgrade"
    rev: "75992aaa40730136014f34227e0135f63fc951b4"  # frozen: v3.21.2
    hooks:
      - id: "pyupgrade"
        name: "Enforce Python 3.10+ idioms"
        args:
          - "--py310-plus"

  - repo: "https://github.com/psf/black-pre-commit-mirror"
    rev: "fa505ab9c3e0fedafe1709fd7ac2b5f8996c670d"  # frozen: 26.3.1
    hooks:
      - id: "black"

  - repo: "https://github.com/pycqa/isort"
    rev: "a333737ed43df02b18e6c95477ea1b285b3de15a"  # frozen: 8.0.1
    hooks:
      - id: "isort"

  - repo: "https://github.com/pycqa/flake8"
    rev: "c48217e1fc006c2dddd14df54e83b67da15de5cd"  # frozen: 7.3.0
    hooks:
      - id: "flake8"
        additional_dependencies:
          - "flake8-toml-config==1.0.0"
          - "flake8-bugbear==25.11.29"

  - repo: "https://github.com/editorconfig-checker/editorconfig-checker"
    rev: "aa06cea887b26f372f9368aa53665266ec6dc364"  # frozen: v3.6.1
    hooks:
      - id: "editorconfig-checker"

  - repo: "https://github.com/python-jsonschema/check-jsonschema"
    rev: "13614ab716a3113145f1294ed259d9fbe5678ff3"  # frozen: 0.37.1
    hooks:
      - id: "check-dependabot"
      - id: "check-github-workflows"
      - id: "check-readthedocs"

  - repo: "https://github.com/rhysd/actionlint"
    rev: "914e7df21a07ef503a81201c76d2b11c789d3fca"  # frozen: v1.7.12
    hooks:
      - id: "actionlint"
        additional_dependencies:
          - "github.com/wasilibs/go-shellcheck/cmd/shellcheck@4e7020840c303923eb1ab846fc446d77be892570"

  - repo: "https://github.com/kurtmckee/pre-commit-hooks"
    rev: "44b638c826f1acd2ba2c5995db3156be60c5efea"  # frozen: v1.0.0
    hooks:
      - id: "verify-consistent-pyproject-toml-python-requirements"
