[tox]
min_version = 4.17.0
envlist =
    build{, -minimum}
    coverage-erase
    test-py{3.14, 3.13, 3.12, 3.11, 3.10}{-chardet, }
    coverage-report
    coverage-html
    docs
    mypy-py{3.14, 3.13, 3.12, 3.11, 3.10}
labels =
    update = update-{pre_commit, requirements}


[testenv]
package = wheel
wheel_build_env = build_wheel
commands =
    python -c "import sys; sys.exit('This is not a runnable tox environment')"


[testenv:build{, -minimum}]
description =
    Test building the project
    minimum: (minimum requirements)
base_python =
    minimum: py3.10
skip_install = true
recreate = true
deps =
    build
    twine
    minimum: poetry-core==2.0.0
    !minimum: poetry-core<3
commands =
    python --version
    python -m build --outdir {envdir}/dist/ --no-isolation
    twine check --strict {envdir}/dist/*


[testenv:test-py{3.14, 3.13, 3.12, 3.11, 3.10}{-chardet, }]
description = Run the test suite ({env_name})
depends =
    coverage-erase
deps =
    -r requirements/test/requirements.txt
    chardet: chardet
commands =
    coverage run -m pytest {posargs:}


[testenv:coverage_base]
description = Base config for coverage-* environments
deps = -r requirements/test/requirements-coverage.txt
skip_install = true


[testenv:coverage-erase]
description = Erase coverage data files
base = coverage_base
commands =
    coverage erase


[testenv:coverage-report]
description = Display a coverage report and verify the fail-under value
base = coverage_base
depends = test-py{3.14, 3.13, 3.12, 3.11, 3.10}{-chardet, }
commands_pre =
    - coverage combine
commands =
    coverage report


[testenv:coverage-html]
description = Create an HTML coverage report
base = coverage_base
depends = coverage-report
commands =
    coverage html --fail-under=0


[testenv:docs]
description = Build and lint the documentation
skip_install = True
base_python = py3.13
deps = -r requirements/docs/requirements.txt
commands =
    sphinx-build -EWq -j auto --keep-going docs/ build/docs/


[testenv:mypy-py{3.14, 3.13, 3.12, 3.11, 3.10}]
description = Test type annotations on Python {py_dot_ver}
deps = -r requirements/mypy/requirements.txt
set_env =
    MYPY_FORCE_COLOR=1
commands =
    mypy {posargs:}


[testenv:update_base]
description = Base for update-* environments
recreate = true
skip_install = true
base_python = py3.14


[testenv:update-requirements]
description = Update requirements
base = update_base
deps =
    poetry
    poetry-plugin-export
commands =
    # Update test requirements
    poetry update --directory="requirements/docs" --lock
    poetry export --directory="requirements/docs" --output="requirements.txt" --without-hashes
    poetry update --directory="requirements/mypy" --lock
    poetry export --directory="requirements/mypy" --output="requirements.txt" --without-hashes
    poetry update --directory="requirements/test" --lock
    poetry export --directory="requirements/test" --output="requirements.txt" --without-hashes
    poetry export --directory="requirements/test" --output="requirements-coverage.txt" --without-hashes --only="coverage"


[testenv:update-pre_commit]
description = Update pre-commit hooks
base = update_base
deps =
    prek
    upadup
commands =
    # Update pre-commit hook versions
    prek autoupdate --freeze
    upadup --freeze
