name: "🧪 Test"

on:
  pull_request:
  push:
    branches:
      - "main"
      - "releases"

jobs:
  test:
    name: "${{ matrix.name }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Linux"
            runner: "ubuntu-latest"
            cpythons:
              - "3.10"
              - "3.11"
              - "3.12"
              - "3.13"
              - "3.14"
            cache-paths:
              - ".mypy_cache/"
            cache-key-hash-files:
              - "docs/conf.py"
              - "pyproject.toml"
              - "requirements/*/requirements.txt"
            tox-skip-environments:
              - "coverage-html"

            # macOS and Windows tests target only the upper and lower CPython versions.
          - name: "macOS"
            runner: "macos-latest"
            cpythons:
              - "3.10"
              - "3.14"
            tox-factors:
              - "chardet"
            cache-key-hash-files:
              - "pyproject.toml"
              - "requirements/*/requirements.txt"

          - name: "Windows"
            runner: "windows-latest"
            cpythons:
              - "3.10"
              - "3.14"
            tox-factors:
              - "chardet"
            cache-key-hash-files:
              - "pyproject.toml"
              - "requirements/*/requirements.txt"

    uses: "kurtmckee/github-workflows/.github/workflows/tox.yaml@01d6d9cea4afa3fbcbfd3e12ce3129b782e093e3" # v2.1
    with:
      config: "${{ toJSON(matrix) }}"
